language: node_js
env:
  matrix:
    - "BROWSER='firefox:19:Windows 2012'"
    - "BROWSER='chrome::Windows 2008'"
branches:
  only:
    - master
    - diffdom
    - beta
    - netflux
node_js:
  - "4.2.1"
before_script:
  - npm run-script lint
  - cp config.js.dist config.js
  - npm install bower
  - ./node_modules/bower/bin/bower install
  - node ./server.js &
  - sleep 2
addons:
  sauce_connect:
    username: "cjdelisle"
    access_key:
      secure: "pgGh8YGXLPq6fpdwwK2jnjRtwXPbVWQ/HIFvwX7E6HBpzxxcF2edE8sCdonWW9TP2LQisZFmVLqoSnZWMnjBr2CBAMKMFvaHQDJDQCo4v3BXkID7KgqyKmNcwW+FPfSJ5MxNBro8/GE/awkhZzJLYGUTS5zi/gVuIUwdi6cHI8s="
